apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: dev
  name: nx-dev
spec:
  containers:
  - image: nginx
    name: nx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
