apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: front-end
  name: front-end
spec:
  containers:
  - image: image
    name: front-end
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
