apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    env: dev
    owner: smarkin
spec:
  # clusterIP: 10.109.37.17 to specify IP into cluster
  # externalTrafficPolicy: Cluster
  ports:
  - name: {{ .Release.Name }}-listener
    port: {{ .Values.ingress.port }}
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
  sessionAffinity: None
  type: ClusterIP