apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: hello-minikube
  name: hello-minikube-service
spec:
  clusterIP: 10.107.126.247
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31132
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: hello-minikube
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost
