# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-18.04-0.1.box"
  config.vm.boot_timeout = 1800
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "5120"
    vb.cpus = "3"
  end
end
