---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app.kubernetes.io/name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      serviceAccountName: aws-load-balancer-controller
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:1.19.6
        ports:
          - name: http
            containerPort: 80
