apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: ping
  name: ping
  namespace: ing-internal
spec:
  containers:
  - image: nginx
    name: ping
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
