apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: big-corp-app
  name: big-corp-app
spec:
  containers:
  - image: busybox
    name: big-corp-app
    command : ["/bin/sh", "-c"]  
    args:
      - i=0; while true; do echo "$(date) INFO $i" >> /var/log/big-corp-app.log;  sleep 1; done;
    resources: {}
    volumeMounts:
    - name: logs
      mountPath: /var/log
  - image: busybox
    name: count-log-1
    command: ["/bin/sh", "-c"]
    args:
      - tail -n+1 -f /var/log/big-corp-app.log
    volumeMounts:
    - name: logs
      mountPath: /var/log
  volumes:
  - name: logs
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
