apiVersion: apps/v1
kind: Deployment
metadata:
    name: simple-nginx
  spec:
    matchLables:
      app: nginx
    replicas: 1
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - name: nginx
          image: nginx:1.19.8
          parts:
          - containerPort: 80