apiVersion: v1
kind: Service
metadata:
  labels:
    env: dev
    owner: smarkin
  name: web-app-service
spec:
  # clusterIP: 10.109.37.17 to specify IP into cluster
  externalTrafficPolicy: Cluster
  ports:
  - name: listener
    nodePort: 31131
    port: 9000
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: web-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost
