apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web-server
  name: web-server
spec:
  containers:
  - image: nginx
    name: web-server
    ports:
      - containerPort: 80
        name: "http-server"
    resources: {}
    volumeMounts:
      - name: data
        mountPath: "/usr/share/nginx/html"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pv-volume1-claim
status: {}
