apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: mongo
  name: mongo
  namespace: my-website
spec:
  containers:
  - image: mongo
    name: mongo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
