apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    resources: {}
    volumeMounts:
    - name: pvc-claim
      mountPath: /srv/app-data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: pvc-claim
      persistentVolumeClaim:
        claimName: srv-pvc
status: {}
