apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: prod
  name: nx-prod
spec:
  containers:
  - image: nginx
    name: nx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
