apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-random
  name: nginx-random
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-random
status:
  loadBalancer: {}
