# - name: add vpn users (ignore errors)
#   # become: true
#   # become_user: root
#   command: "{{ softether_dir }}/vpncmd /SERVER 127.0.0.1 /HUB:{{ vpn_hub.name }} /CMD {{ item }}"
#   loop:
#     - UserCreate {{ vpn_user.name }} /GROUP:none /REALNAME:none /NOTE:none
#     - UserPasswordSet {{ vpn_user.name }} /PASSWORD:{{ vpn_user.pass }}
#   ignore_errors: true

- name: Run server softether
  service:
    name: softether
    state: started

- name: Create groups
  command: "{{ softether_dir }}/vpncmd /SERVER 127.0.0.1 /hub:{{ vpn_hub.name }} /cmd GroupCreate {{ item }} /RealName:none /Note:none"
  with_items: "{{ vpn_groups }}"

- name: Create users
  command: "{{ softether_dir }}/vpncmd /SERVER 127.0.0.1 /hub:{{ vpn_hub.name }} /cmd UserCreate {{ item.name }} /group:{{ item.groups | first }} /RealName:none /Note:none"
  with_items: "{{ vpn_users }}"

- name: Set passwords
  command: "{{ softether_dir }}/vpncmd /SERVER 127.0.0.1 /hub:{{ vpn_hub.name }} /cmd UserPasswordSet {{ item.name }} /password:{{ item.pass }}"
  with_items: "{{ vpn_users }}"

- name: enable L2TP over IPsec
  # become: true
  # become_user: root
  command: >
    {{ softether_dir }}/vpncmd /SERVER 127.0.0.1 /ADMINHUB:{{ vpn_hub.name }} /cmd
    IPsecEnable /L2TP:yes /L2TPRAW:no /ETHERIP:no /PSK:{{ vpn_shared_pass }} /DEFAULTHUB:{{ vpn_hub.name }}

- name: additional settings
  # become: true
  # become_user: root
  command: "{{ softether_dir }}/vpncmd /SERVER 127.0.0.1 /HUB:{{ vpn_hub.name }} /cmd {{ item }}"
  loop:
    - SecureNatEnable
    - NatEnable
    - DHCPEnable

- name: Set Admin Password
  command: "{{ softether_dir }}/vpncmd /SERVER 127.0.0.1 /hub:default /CMD SetHubPassword {{ vpn_admin_pass }}"