apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-env
  name: pod-env
spec:
  containers:
  - env:
    - name: var1
      value: value
    image: nginx
    name: pod-env
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
