Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  #config.ssh.insert_key = true
  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu"
    vb.memory = "5120"
    vb.cpus = "2"
  end
  config.vm.synced_folder "../../labs", "/home/vagrant/labs"
  config.vm.provision "shell", path: "./scripts/shell_setup.sh"
  config.vm.provision "shell", path: "./scripts/build_setup.sh"
  #config.vm.provision "shell", path: "https://training.linuxfoundation.org/cm/prep/ready-for.sh", args: "--install LFS301", privileged: false
end