---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: default
  labels:
    app.kubernetes.io/name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web
    spec:
      serviceAccountName: aws-load-balancer-controller
      containers:
      - name: web
        image: 500480925365.dkr.ecr.eu-north-1.amazonaws.com/simple_app:0.0.3
        ports:
          - name: http
            containerPort: 8080
      imagePullSecrets:
        - name: regcred