apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip

spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80