apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: srv-pvc
  namespace: default
spec:
  storageClassName: "app-data" 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
