apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-data
  labels:
    type: local
    app: app-data
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /srv/app-data

