apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-secrets-via-env
  name: pod-secrets-via-env
  namespace: redis
spec:
  containers:
  - image: redis
    name: pod-secrets-via-env
    env:
      - name: CONFIDENTIAL
        valueFrom:
          secretKeyRef:
            name: super-secret
            key: password
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
