apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-secrets-via-file
  name: pod-secrets-via-file
  namespace: redis
spec:
  volumes:
    - name: secrets
      secret:
        secretName: super-secret
  containers:
  - image: redis
    name: pod-secrets-via-file
    resources: {}
    volumeMounts:
      - name: secrets
        mountPath: /secrets
        readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
