apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name:  base
  region: eu-north-1

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      # if no namespace is set, "default" will be used;
      # the namespace will be created if it doesn't exist already
      namespace: default
      labels: { aws-usage: "application"}
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
    - "arn:aws:iam::500480925365:policy/eks-console-dashboard-full-access-group"
    - "arn:aws:iam::500480925365:policy/AWSLoadBalancerControllerIAMPolicy"

nodeGroups:
  - name: ng-1
    instanceType: t3.micro
    desiredCapacity: 2
    volumeSize: 20
    labels:
      role: worker
    tags: 
      nodegroup-role: worker
      owner: "markin"
      requester: "home"
      role: "test"
      env: "dev"
    
cloudWatch:
    clusterLogging:
        # enable specific types of cluster control plane logs
        enableTypes: ["audit", "authenticator", "controllerManager"]